### ISSUE TITLE
script gets stuck on IPA file due to download fail

### ISSUE THREAD

**Issue by LittlePlanetCD** [Phil564/testflight_bulk_downloader#1]
was trying to run this on my own machine, but the download for 184270730be59531836b96615c04476a.ipa is constantly failing for me

the script should have a failsafe for this i think

**Comment by LittlePlanetCD** [comment]
this is the error btw
![image](https://github.com/Phil564/testflight_bulk_downloader/assets/24783625/dba730a5-748c-4f30-905b-d359a8809f61)

**Comment by Phil564** [comment]
I am currently working on a fix. For now, just add this url to filelist.txt. It should skip the file.

https://d193ln56du8muy.cloudfront.net/ipas/10104/1353084429/184270730be59531836b96615c04476a.ipa

**Comment by Phil564** [comment]
Fixed.
